### ISSUE TITLE
Moving on from my account

### ISSUE THREAD

**Issue by qrush** [pickaxe-club/pickaxe.club#2]
So all of my github coupons have expired. I think pickaxe.club should consider moving this repo elsewhere or the ownership of it to be transferred.

I'm still seeing this on my billing:

<img width="636" alt="screen shot 2017-07-07 at 15 59 26" src="https://user-images.githubusercontent.com/12610/27960935-5b26ad84-632d-11e7-8bcc-dc491e52f089.png">

And my git creds (or something?) are being used to commit to this repo. I'm not in a urgent need to move off of stuff here but I'd like to make sure this gets moving at some point soon. 🙏 ⛏

**Comment by ravenx99** [comment]
Okay, I didn't realize there was something that could still cost you money here.  Wasn't actually aware that the world was being pushed to both Amazon and Github, too.

Kevin is handling this end of things... we'll discuss in Slack and decide what to do with it.

**Comment by qrush** [comment]
i'm not paying for Git LFS, it just made me realize that my creds are being used here still. No worries.

**Comment by kkuchta** [comment]
Oh hey, I totally missed this discussion!

Ravenx did mention this in slack.  I've moved a few things over:
- We're now using https://github.com/kkuchta/pickaxe-boot/ instead of your copy of that repo to boot the server
- Pulling and pushing the non-data-file backups to https://github.com/pickaxe-club/pickaxe.club now uses a non-nick ssh key.

Anything else you'd like migrated off of your creds?

**Comment by qrush** [comment]
Yay! That's all I know of. Danke :bowtie: ⛏
